# Generated by Django 5.2.13 on 2026-04-27 18:31

import django.db.models.deletion
import production.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Название')),
                ('production_type', models.CharField(choices=[('3d_print', '3D-печать'), ('laser_cut', 'Лазерная резка'), ('both', 'Оба типа')], default='both', max_length=20, verbose_name='Тип производства')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
            ],
            options={
                'verbose_name': 'Материал',
                'verbose_name_plural': 'Материалы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160, verbose_name='Название заказа')),
                ('production_type', models.CharField(choices=[('3d_print', '3D-печать'), ('laser_cut', 'Лазерная резка')], max_length=20, verbose_name='Тип производства')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('photo', models.ImageField(blank=True, upload_to=production.models.order_photo_upload_to, verbose_name='Фото модели')),
                ('production_file', models.FileField(upload_to=production.models.order_file_upload_to, verbose_name='Производственный файл')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('in_progress', 'В работе'), ('done', 'Готово'), ('cancelled', 'Отменено')], default='pending', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='production.material', verbose_name='Материал')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['created_at'],
            },
        ),
    ]
