# Generated by Django 5.2.13 on 2026-04-27 19:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_seed_materials'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='rejection_reason',
            field=models.TextField(blank=True, verbose_name='Причина отклонения'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает'), ('in_progress', 'В работе'), ('done', 'Готово'), ('cancelled', 'Отменено'), ('rejected', 'Отклонено')], default='pending', max_length=20, verbose_name='Статус'),
        ),
        migrations.CreateModel(
            name='OrderStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.PositiveIntegerField(verbose_name='Номер заказа')),
                ('order_title', models.CharField(max_length=160, verbose_name='Название заказа')),
                ('old_status', models.CharField(choices=[('pending', 'Ожидает'), ('in_progress', 'В работе'), ('done', 'Готово'), ('cancelled', 'Отменено'), ('rejected', 'Отклонено')], max_length=20, verbose_name='Старый статус')),
                ('new_status', models.CharField(choices=[('pending', 'Ожидает'), ('in_progress', 'В работе'), ('done', 'Готово'), ('cancelled', 'Отменено'), ('rejected', 'Отклонено')], max_length=20, verbose_name='Новый статус')),
                ('reason', models.TextField(blank=True, verbose_name='Причина')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата изменения')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_status_changes', to=settings.AUTH_USER_MODEL, verbose_name='Администратор')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_logs', to='production.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Изменение статуса',
                'verbose_name_plural': 'Изменения статусов',
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
