# Generated by Django 5.2.13 on 2026-05-28 16:59

import django.db.models.deletion
import production.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0007_rejectionreason'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='color',
            field=models.CharField(default='Любой цвет', max_length=40, verbose_name='Цвет'),
        ),
        migrations.AddField(
            model_name='order',
            name='admin_comment',
            field=models.TextField(blank=True, verbose_name='Комментарий администратора'),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=80, verbose_name='Действие')),
                ('target_type', models.CharField(max_length=80, verbose_name='Тип объекта')),
                ('target_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID объекта')),
                ('target_label', models.CharField(blank=True, max_length=255, verbose_name='Объект')),
                ('changes', models.TextField(blank=True, verbose_name='Изменения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Событие аудита',
                'verbose_name_plural': 'Аудит',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='OrderDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('production_type', models.CharField(choices=[('3d_print', '3D-печать'), ('laser_cut', 'Лазерная резка')], max_length=20, verbose_name='Тип производства')),
                ('title', models.CharField(blank=True, max_length=30, verbose_name='Название заказа')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('photo', models.ImageField(blank=True, upload_to=production.models.order_draft_photo_upload_to, verbose_name='Фото модели')),
                ('production_file', models.FileField(blank=True, upload_to=production.models.order_draft_file_upload_to, verbose_name='Производственный файл')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('current_step', models.CharField(default='title', max_length=20, verbose_name='Текущий шаг')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_drafts', to='production.material', verbose_name='Материал')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_drafts', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Черновик заказа',
                'verbose_name_plural': 'Черновики заказов',
                'ordering': ['-updated_at', '-id'],
            },
        ),
    ]
