# Generated by Django 5.2.13 on 2026-05-29 07:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0008_material_color_order_admin_comment_auditlog_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pickup_cell',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Ячейка выдачи'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(condition=models.Q(('pickup_cell__isnull', False), ('status', 'ready')), fields=('pickup_cell',), name='unique_ready_order_pickup_cell'),
        ),
    ]
