# Generated by Django 5.2.13 on 2026-05-29 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0009_order_pickup_cell_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='order',
            name='unique_ready_order_pickup_cell',
        ),
    ]
