# Generated by Django 5.2.13 on 2026-08-06 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0010_remove_order_unique_ready_order_pickup_cell'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_priority',
            field=models.BooleanField(default=False, verbose_name='Приоритетный заказ'),
        ),
        migrations.AddField(
            model_name='order',
            name='priority_remaining_quantity',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Осталось копий к запуску'),
        ),
    ]
