# Generated by Django 5.2.13 on 2026-08-06 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0011_order_is_priority_order_priority_remaining_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='PinnedAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80, verbose_name='Заголовок')),
                ('body', models.TextField(verbose_name='Текст объявления')),
                ('is_active', models.BooleanField(default=True, verbose_name='Закреплено')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Закрепленное объявление',
                'verbose_name_plural': 'Закрепленные объявления',
                'ordering': ['-is_active', '-updated_at', '-id'],
            },
        ),
    ]
