# Generated by Django 5.2.13 on 2026-08-06 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0013_countdown'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderPrefixRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(max_length=20, verbose_name='Префикс')),
                ('starts_on', models.DateField(verbose_name='Начало периода')),
                ('ends_on', models.DateField(verbose_name='Конец периода')),
                ('next_number', models.PositiveIntegerField(default=1, verbose_name='Следующий номер')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Правило префикса заказа',
                'verbose_name_plural': 'Правила префиксов заказов',
                'ordering': ['-starts_on', '-id'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='prefix_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Номер в префиксе'),
        ),
        migrations.AddField(
            model_name='order',
            name='prefix_text',
            field=models.CharField(blank=True, max_length=20, verbose_name='Префикс номера'),
        ),
        migrations.AddField(
            model_name='order',
            name='prefix_rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='production.orderprefixrule', verbose_name='Правило префикса'),
        ),
    ]
