# Generated by Django 5.2.13 on 2026-08-06 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0014_orderprefixrule_order_prefix_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DutySlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=80, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=80, verbose_name='Фамилия')),
                ('unload_time', models.TimeField(verbose_name='Время разгрузки очереди')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Дежурство',
                'verbose_name_plural': 'График дежурства',
                'ordering': ['unload_time', 'last_name', 'first_name', 'id'],
            },
        ),
    ]
