# Generated by Django 5.2.13 on 2026-08-06 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0015_dutyslot'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dutyslot',
            options={'ordering': ['weekday', 'unload_time', 'last_name', 'first_name', 'id'], 'verbose_name': 'Дежурство', 'verbose_name_plural': 'График дежурства'},
        ),
        migrations.AddField(
            model_name='dutyslot',
            name='weekday',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Понедельник'), (1, 'Вторник'), (2, 'Среда'), (3, 'Четверг'), (4, 'Пятница'), (5, 'Суббота'), (6, 'Воскресенье')], default=0, verbose_name='День недели'),
        ),
        migrations.CreateModel(
            name='DutySkip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unavailable_date', models.DateField(verbose_name='Дата пропуска')),
                ('unavailable_time', models.TimeField(verbose_name='Время пропуска')),
                ('reason', models.TextField(verbose_name='Причина')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('duty_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skips', to='production.dutyslot', verbose_name='Дежурный')),
                ('replacement_slot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='replacements', to='production.dutyslot', verbose_name='Заменяющий')),
            ],
            options={
                'verbose_name': 'Пропуск дежурства',
                'verbose_name_plural': 'Пропуски дежурства',
                'ordering': ['-unavailable_date', 'unavailable_time', 'duty_slot_id', 'id'],
            },
        ),
    ]
