# Generated by Django 5.2.13 on 2026-08-06 14:06

import django.db.models.deletion
from django.db import migrations, models


def migrate_duty_people(apps, schema_editor):
    DutyPerson = apps.get_model("production", "DutyPerson")
    DutySlot = apps.get_model("production", "DutySlot")
    DutySkip = apps.get_model("production", "DutySkip")
    people_by_name = {}

    for slot in DutySlot.objects.all().order_by("id"):
        first_name = (slot.first_name or "").strip()
        last_name = (slot.last_name or "").strip()
        if not first_name or not last_name:
            continue
        key = (last_name.casefold(), first_name.casefold())
        person = people_by_name.get(key)
        if person is None:
            person, _ = DutyPerson.objects.get_or_create(
                last_name=last_name,
                first_name=first_name,
                defaults={"is_active": slot.is_active},
            )
            people_by_name[key] = person
        slot.person_id = person.pk
        slot.save(update_fields=["person"])

    for skip in DutySkip.objects.select_related("replacement_slot").all():
        if skip.replacement_slot_id and skip.replacement_slot.person_id:
            skip.replacement_person_id = skip.replacement_slot.person_id
            skip.save(update_fields=["replacement_person"])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0016_alter_dutyslot_options_dutyslot_weekday_dutyskip'),
    ]

    operations = [
        migrations.CreateModel(
            name='DutyPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=80, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=80, verbose_name='Фамилия')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Дежурный',
                'verbose_name_plural': 'Дежурные',
                'ordering': ['last_name', 'first_name', 'id'],
            },
        ),
        migrations.AlterModelOptions(
            name='dutyslot',
            options={'ordering': ['weekday', 'unload_time', 'person__last_name', 'person__first_name', 'last_name', 'first_name', 'id'], 'verbose_name': 'Дежурство', 'verbose_name_plural': 'График дежурства'},
        ),
        migrations.AlterField(
            model_name='dutyskip',
            name='replacement_slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='replacements', to='production.dutyslot', verbose_name='Заменяющий'),
        ),
        migrations.AlterField(
            model_name='dutyslot',
            name='first_name',
            field=models.CharField(blank=True, max_length=80, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='dutyslot',
            name='last_name',
            field=models.CharField(blank=True, max_length=80, verbose_name='Фамилия'),
        ),
        migrations.AddField(
            model_name='dutyskip',
            name='replacement_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='replacement_skips', to='production.dutyperson', verbose_name='Заменяющий'),
        ),
        migrations.AddField(
            model_name='dutyslot',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slots', to='production.dutyperson', verbose_name='Дежурный'),
        ),
        migrations.RunPython(migrate_duty_people, noop_reverse),
    ]
