# Generated by Django 5.2.13 on 2026-08-06 14:41

import django.db.models.deletion
from django.db import migrations, models


WEEKDAY_LABELS = {
    0: "Понедельник",
    1: "Вторник",
    2: "Среда",
    3: "Четверг",
    4: "Пятница",
    5: "Суббота",
    6: "Воскресенье",
}


def migrate_weekday_slots_to_schedules(apps, schema_editor):
    DutySchedule = apps.get_model("production", "DutySchedule")
    DutyScheduleRule = apps.get_model("production", "DutyScheduleRule")
    DutySlot = apps.get_model("production", "DutySlot")

    for weekday, label in WEEKDAY_LABELS.items():
        slots = DutySlot.objects.filter(weekday=weekday)
        if not slots.exists():
            continue
        schedule = DutySchedule.objects.create(name=label, is_active=True)
        slots.update(schedule=schedule)
        DutyScheduleRule.objects.create(weekday=weekday, schedule=schedule, is_active=True)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0017_dutyperson_alter_dutyslot_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DutySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название графика')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'График дежурства',
                'verbose_name_plural': 'Графики дежурства',
                'ordering': ['name', 'id'],
            },
        ),
        migrations.AlterModelOptions(
            name='dutyslot',
            options={'ordering': ['schedule__name', 'weekday', 'unload_time', 'person__last_name', 'person__first_name', 'last_name', 'first_name', 'id'], 'verbose_name': 'Дежурство', 'verbose_name_plural': 'График дежурства'},
        ),
        migrations.AddField(
            model_name='dutyslot',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='production.dutyschedule', verbose_name='График'),
        ),
        migrations.CreateModel(
            name='DutyScheduleRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'Понедельник'), (1, 'Вторник'), (2, 'Среда'), (3, 'Четверг'), (4, 'Пятница'), (5, 'Суббота'), (6, 'Воскресенье')], unique=True, verbose_name='День недели')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='weekday_rules', to='production.dutyschedule', verbose_name='График')),
            ],
            options={
                'verbose_name': 'Правило графика',
                'verbose_name_plural': 'Правила графиков',
                'ordering': ['weekday', 'id'],
            },
        ),
        migrations.RunPython(migrate_weekday_slots_to_schedules, noop_reverse),
    ]
