# Generated by Django 5.2.13 on 2026-08-06 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0018_dutyschedule_alter_dutyslot_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allow_self_pickup', models.BooleanField(default=True, verbose_name='Разрешить самосъём заказов')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Настройка производства',
                'verbose_name_plural': 'Настройки производства',
            },
        ),
    ]
