# Generated by Django 5.2.13 on 2026-09-08 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0020_dutyperson_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='model_depth',
            field=models.FloatField(blank=True, null=True, verbose_name='Глубина модели'),
        ),
        migrations.AddField(
            model_name='order',
            name='model_height',
            field=models.FloatField(blank=True, null=True, verbose_name='Высота модели'),
        ),
        migrations.AddField(
            model_name='order',
            name='model_width',
            field=models.FloatField(blank=True, null=True, verbose_name='Ширина модели'),
        ),
        migrations.AddField(
            model_name='orderdraft',
            name='model_depth',
            field=models.FloatField(blank=True, null=True, verbose_name='Глубина модели'),
        ),
        migrations.AddField(
            model_name='orderdraft',
            name='model_height',
            field=models.FloatField(blank=True, null=True, verbose_name='Высота модели'),
        ),
        migrations.AddField(
            model_name='orderdraft',
            name='model_width',
            field=models.FloatField(blank=True, null=True, verbose_name='Ширина модели'),
        ),
    ]
