# Generated by Django 5.2.13 on 2026-09-08 14:06

import django.db.models.deletion
import production.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0021_order_model_depth_order_model_height_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdraft',
            name='is_priority',
            field=models.BooleanField(default=False, verbose_name='Приоритетный заказ'),
        ),
        migrations.CreateModel(
            name='OrderMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, verbose_name='Сообщение')),
                ('photo', models.ImageField(blank=True, upload_to=production.models.order_message_photo_upload_to, verbose_name='Фото')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_messages', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='production.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Сообщение по заказу',
                'verbose_name_plural': 'Сообщения по заказам',
                'ordering': ['created_at', 'id'],
            },
        ),
    ]
