# Generated by Django 5.2.13 on 2026-10-03 17:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.utils import timezone


def seed_account_activity(apps, schema_editor):
    User = apps.get_model("auth", "User")
    AccountActivity = apps.get_model("production", "AccountActivity")
    now = timezone.now()
    activities = []
    for user in User.objects.all().only("id", "last_login", "date_joined").iterator():
        last_seen_at = user.last_login or user.date_joined or now
        activities.append(AccountActivity(user_id=user.pk, last_seen_at=last_seen_at))
    AccountActivity.objects.bulk_create(activities, ignore_conflicts=True)


def clear_account_activity(apps, schema_editor):
    AccountActivity = apps.get_model("production", "AccountActivity")
    AccountActivity.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0023_seed_semi_printer_group'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_seen_at', models.DateTimeField(db_index=True, verbose_name='Последняя активность')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account_activity', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Активность аккаунта',
                'verbose_name_plural': 'Активность аккаунтов',
                'ordering': ['-last_seen_at', '-id'],
            },
        ),
        migrations.RunPython(seed_account_activity, clear_account_activity),
    ]
