from django.contrib.auth import views as auth_views
from django.urls import path

from . import views

urlpatterns = [
    path("", views.home, name="home"),
    path("register/", views.register, name="register"),
    path(
        "login/",
        auth_views.LoginView.as_view(template_name="registration/login.html"),
        name="login",
    ),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("orders/", views.order_list, name="orders"),
    path("orders/new/", views.order_create, name="order_create"),
    path("orders/new/photo-preview/", views.order_wizard_photo_preview, name="order_wizard_photo_preview"),
    path("orders/new/source-file/", views.order_wizard_source_file, name="order_wizard_source_file"),
    path("orders/new/preview/", views.order_wizard_preview_save, name="order_wizard_preview_save"),
    path("orders/drafts/<int:pk>/continue/", views.order_draft_continue, name="order_draft_continue"),
    path("orders/drafts/<int:pk>/delete/", views.order_draft_delete, name="order_draft_delete"),
    path("orders/<int:pk>/file/", views.order_file_download, name="order_file_download"),
    path("orders/<int:pk>/repeat/", views.order_repeat, name="order_repeat"),
    path("orders/<int:pk>/", views.order_detail, name="order_detail"),
    path("orders/<int:pk>/messages/", views.order_message_create, name="order_message_create"),
    path("orders/<int:pk>/cancel/confirm/", views.order_cancel_confirm, name="order_cancel_confirm"),
    path("orders/<int:pk>/cancel/", views.order_cancel, name="order_cancel"),
    path("orders/<int:pk>/confirm-receipt/", views.order_confirm_receipt, name="order_confirm_receipt"),
    path("orders/<int:pk>/self-pickup/", views.order_self_pickup, name="order_self_pickup"),
    path("admin-panel/dashboard/", views.admin_dashboard, name="admin_dashboard"),
    path("admin-panel/orders/", views.admin_order_queue, name="admin_order_queue"),
    path("admin-panel/orders/ready/", views.admin_order_ready, name="admin_order_ready"),
    path("admin-panel/orders/archive/", views.admin_order_archive, name="admin_order_archive"),
    path("admin-panel/orders/export/", views.admin_order_export, name="admin_order_export"),
    path(
        "admin-panel/orders/ready/export/",
        views.admin_order_export,
        {"list_kind": "ready"},
        name="admin_order_ready_export",
    ),
    path(
        "admin-panel/orders/archive/export/",
        views.admin_order_export,
        {"list_kind": "archive"},
        name="admin_order_archive_export",
    ),
    path("admin-panel/orders/bulk-status/", views.admin_orders_bulk_status_update, name="admin_orders_bulk_status_update"),
    path("production/orders/<int:pk>/mark-ready/", views.production_order_mark_ready, name="production_order_mark_ready"),
    path(
        "admin-panel/orders/<int:pk>/priority-print/",
        views.admin_order_priority_print_batch,
        name="admin_order_priority_print_batch",
    ),
    path(
        "admin-panel/orders/<int:pk>/quick-status/",
        views.admin_order_quick_status,
        name="admin_order_quick_status",
    ),
    path("admin-panel/orders/<int:pk>/update/", views.admin_order_update, name="admin_order_update"),
    path("admin-panel/bulk/", views.bulk_order_create, name="bulk_order_create"),
    path("admin-panel/bulk/files/<str:token>/", views.bulk_order_source_file, name="bulk_order_source_file"),
    path("admin-panel/bulk/previews/<str:token>/", views.bulk_order_preview_save, name="bulk_order_preview_save"),
    path("admin-panel/bulk/previews/<str:token>/image/", views.bulk_order_preview_file, name="bulk_order_preview_file"),
    path("admin-panel/materials/", views.material_list, name="material_list"),
    path("admin-panel/materials/new/", views.material_create, name="material_create"),
    path("admin-panel/materials/<int:pk>/", views.material_update, name="material_update"),
    path("admin-panel/materials/<int:pk>/delete/", views.material_delete, name="material_delete"),
    path("admin-panel/rejection-reasons/", views.rejection_reason_list, name="rejection_reason_list"),
    path("admin-panel/rejection-reasons/new/", views.rejection_reason_create, name="rejection_reason_create"),
    path(
        "admin-panel/rejection-reasons/<int:pk>/",
        views.rejection_reason_update,
        name="rejection_reason_update",
    ),
    path(
        "admin-panel/rejection-reasons/<int:pk>/delete/",
        views.rejection_reason_delete,
        name="rejection_reason_delete",
    ),
    path("admin-panel/info/", views.info_panel, name="info_panel"),
    path("admin-panel/announcements/", views.announcement_list, name="announcement_list"),
    path("admin-panel/announcements/new/", views.announcement_create, name="announcement_create"),
    path("admin-panel/announcements/<int:pk>/", views.announcement_update, name="announcement_update"),
    path("admin-panel/announcements/<int:pk>/delete/", views.announcement_delete, name="announcement_delete"),
    path("admin-panel/countdowns/", views.countdown_list, name="countdown_list"),
    path("admin-panel/countdowns/new/", views.countdown_create, name="countdown_create"),
    path("admin-panel/countdowns/<int:pk>/", views.countdown_update, name="countdown_update"),
    path("admin-panel/countdowns/<int:pk>/delete/", views.countdown_delete, name="countdown_delete"),
    path("admin-panel/duty/", views.duty_slot_list, name="duty_slot_list"),
    path("admin-panel/duty/day/<int:weekday>/", views.duty_slot_day_update, name="duty_slot_day_update"),
    path("admin-panel/duty/schedules/new/", views.duty_schedule_create, name="duty_schedule_create"),
    path("admin-panel/duty/schedules/<int:pk>/", views.duty_schedule_update, name="duty_schedule_update"),
    path("admin-panel/duty/schedules/<int:pk>/edit/", views.duty_schedule_edit, name="duty_schedule_edit"),
    path("admin-panel/duty/schedules/<int:pk>/delete/", views.duty_schedule_delete, name="duty_schedule_delete"),
    path("admin-panel/duty/rules/new/", views.duty_schedule_rule_create, name="duty_schedule_rule_create"),
    path("admin-panel/duty/rules/<int:pk>/", views.duty_schedule_rule_update, name="duty_schedule_rule_update"),
    path("admin-panel/duty/rules/<int:pk>/delete/", views.duty_schedule_rule_delete, name="duty_schedule_rule_delete"),
    path("admin-panel/duty/people/new/", views.duty_person_create, name="duty_person_create"),
    path("admin-panel/duty/people/<int:pk>/", views.duty_person_update, name="duty_person_update"),
    path("admin-panel/duty/people/<int:pk>/delete/", views.duty_person_delete, name="duty_person_delete"),
    path("admin-panel/duty/new/", views.duty_slot_create, name="duty_slot_create"),
    path("admin-panel/duty/<int:pk>/", views.duty_slot_update, name="duty_slot_update"),
    path("admin-panel/duty/<int:pk>/delete/", views.duty_slot_delete, name="duty_slot_delete"),
    path("admin-panel/duty/skips/new/", views.duty_skip_create, name="duty_skip_create"),
    path("admin-panel/duty/skips/<int:pk>/", views.duty_skip_update, name="duty_skip_update"),
    path("admin-panel/duty/skips/<int:pk>/delete/", views.duty_skip_delete, name="duty_skip_delete"),
    path("admin-panel/prefix-rules/", views.prefix_rule_list, name="prefix_rule_list"),
    path("admin-panel/prefix-rules/new/", views.prefix_rule_create, name="prefix_rule_create"),
    path("admin-panel/prefix-rules/<int:pk>/", views.prefix_rule_update, name="prefix_rule_update"),
    path(
        "admin-panel/prefix-rules/<int:pk>/delete-orders/",
        views.prefix_rule_delete_orders,
        name="prefix_rule_delete_orders",
    ),
    path("admin-panel/prefix-rules/<int:pk>/delete/", views.prefix_rule_delete, name="prefix_rule_delete"),
    path("admin-panel/users/", views.user_list, name="user_list"),
    path("admin-panel/users/bulk-delete/", views.user_bulk_delete, name="user_bulk_delete"),
    path("admin-panel/users/<int:pk>/stats/", views.user_stats, name="user_stats"),
    path("admin-panel/users/<int:pk>/admin/", views.user_admin_toggle, name="user_admin_toggle"),
    path("admin-panel/users/<int:pk>/semi-printer/", views.user_semi_printer_toggle, name="user_semi_printer_toggle"),
    path("admin-panel/users/<int:pk>/delete/", views.user_delete, name="user_delete"),
    path("admin-panel/status-log/", views.status_log_list, name="status_log_list"),
    path("admin-panel/audit/", views.audit_log_list, name="audit_log_list"),
    path("admin-panel/health/", views.system_health, name="system_health"),
]
